// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu3l9S7CEil9u1o0Bbx-7eNdPdJNb04fA',
    appId: '1:1084930896982:web:8c94485cc4cc2c5d8b77f7',
    messagingSenderId: '1084930896982',
    projectId: 'brand-bridge-6c138',
    authDomain: 'brand-bridge-6c138.firebaseapp.com',
    storageBucket: 'brand-bridge-6c138.appspot.com',
    measurementId: 'G-X9S85JDKWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB36uXXwGMg0KKed9lWy9T37UWCcnyWbDc',
    appId: '1:1084930896982:android:e1b2a43410e3d9298b77f7',
    messagingSenderId: '1084930896982',
    projectId: 'brand-bridge-6c138',
    storageBucket: 'brand-bridge-6c138.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0MVHMUso7vQSTkoxQu1pzqKyC5jTsAT4',
    appId: '1:1084930896982:ios:e52fedf89eafd1e48b77f7',
    messagingSenderId: '1084930896982',
    projectId: 'brand-bridge-6c138',
    storageBucket: 'brand-bridge-6c138.appspot.com',
    iosBundleId: 'com.example.brandBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0MVHMUso7vQSTkoxQu1pzqKyC5jTsAT4',
    appId: '1:1084930896982:ios:e52fedf89eafd1e48b77f7',
    messagingSenderId: '1084930896982',
    projectId: 'brand-bridge-6c138',
    storageBucket: 'brand-bridge-6c138.appspot.com',
    iosBundleId: 'com.example.brandBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu3l9S7CEil9u1o0Bbx-7eNdPdJNb04fA',
    appId: '1:1084930896982:web:2882c19bb28648ed8b77f7',
    messagingSenderId: '1084930896982',
    projectId: 'brand-bridge-6c138',
    authDomain: 'brand-bridge-6c138.firebaseapp.com',
    storageBucket: 'brand-bridge-6c138.appspot.com',
    measurementId: 'G-Z22PKVL0BE',
  );
}
